version: '3.7'

services:
  frontend:
    container_name: frontend
    build: 
        context: ./frontend
        dockerfile: Dockerfile-frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true